name: Flutter Web Deploy

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            my_secret: ${{ secrets.GH_TOKEN }}

        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
            - run: flutter build web --release --base-href /NoteNinja/
            - run: git config user.name github-actions
            - run: git config user.email github-actions@github.com
            - run: git --work-tree build/web add --all
            - run: git commit -m "Automatic deployment by github-actions"
            - name: Push changes
              run: |
                  git remote add orign https://${{ secrets.GH_TOKEN }}@github.com/aarnros/NoteNinja.git
                  git push origin HEAD:gh-pages --force
