name: Flutter Web Deploy

on:
    push:
        branches:
            - master

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            my_secret: ${{ secrets.GH_TOKEN }}

        steps:
            - uses: actions/checkout@v3
            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"

            - run: flutter clean
            - run: flutter pub get
            - run: flutter build web --release

            - run: |
                  cd build
                  mkdir web-deploy
                  cd web-deploy
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git init
                  git remote add origin https://${{secrets.GH_TOKEN}}@github.com/aarnros/NoteNinja.git
                  git fetch origin gh-pages
                  git switch gh-pages
                  cp -R ../web/* .
                  git status
                  git add .
                  git commit -m "Deploying to gh-pages"
                  git push origin gh-pages
